# coding: utf-8

"""
    nebula-api

    The public Nebula Labs API for access to pertinent UT Dallas data

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class SchemaMazevoEvent(BaseModel):
    """
    SchemaMazevoEvent
    """ # noqa: E501
    contact_name: Optional[StrictStr] = Field(default=None, alias="contactName")
    date_time_end: Optional[StrictStr] = Field(default=None, alias="dateTimeEnd")
    date_time_start: Optional[StrictStr] = Field(default=None, alias="dateTimeStart")
    event_name: Optional[StrictStr] = Field(default=None, alias="eventName")
    organization_name: Optional[StrictStr] = Field(default=None, alias="organizationName")
    setup_minutes: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="setupMinutes")
    status_color: Optional[StrictStr] = Field(default=None, alias="statusColor")
    status_description: Optional[StrictStr] = Field(default=None, alias="statusDescription")
    teardown_minutes: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="teardownMinutes")
    __properties: ClassVar[List[str]] = ["contactName", "dateTimeEnd", "dateTimeStart", "eventName", "organizationName", "setupMinutes", "statusColor", "statusDescription", "teardownMinutes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SchemaMazevoEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SchemaMazevoEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "contactName": obj.get("contactName"),
            "dateTimeEnd": obj.get("dateTimeEnd"),
            "dateTimeStart": obj.get("dateTimeStart"),
            "eventName": obj.get("eventName"),
            "organizationName": obj.get("organizationName"),
            "setupMinutes": obj.get("setupMinutes"),
            "statusColor": obj.get("statusColor"),
            "statusDescription": obj.get("statusDescription"),
            "teardownMinutes": obj.get("teardownMinutes")
        })
        return _obj


