# coding: utf-8

"""
    nebula-api

    The public Nebula Labs API for access to pertinent UT Dallas data

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.schema_location import SchemaLocation
from openapi_client.models.schema_meeting import SchemaMeeting
from typing import Optional, Set
from typing_extensions import Self

class SchemaProfessor(BaseModel):
    """
    SchemaProfessor
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, alias="_id")
    email: Optional[StrictStr] = None
    first_name: Optional[StrictStr] = None
    image_uri: Optional[StrictStr] = None
    last_name: Optional[StrictStr] = None
    office: Optional[SchemaLocation] = None
    office_hours: Optional[List[SchemaMeeting]] = None
    phone_number: Optional[StrictStr] = None
    profile_uri: Optional[StrictStr] = None
    sections: Optional[List[StrictStr]] = None
    titles: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["_id", "email", "first_name", "image_uri", "last_name", "office", "office_hours", "phone_number", "profile_uri", "sections", "titles"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SchemaProfessor from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of office
        if self.office:
            _dict['office'] = self.office.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in office_hours (list)
        _items = []
        if self.office_hours:
            for _item_office_hours in self.office_hours:
                if _item_office_hours:
                    _items.append(_item_office_hours.to_dict())
            _dict['office_hours'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SchemaProfessor from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "email": obj.get("email"),
            "first_name": obj.get("first_name"),
            "image_uri": obj.get("image_uri"),
            "last_name": obj.get("last_name"),
            "office": SchemaLocation.from_dict(obj["office"]) if obj.get("office") is not None else None,
            "office_hours": [SchemaMeeting.from_dict(_item) for _item in obj["office_hours"]] if obj.get("office_hours") is not None else None,
            "phone_number": obj.get("phone_number"),
            "profile_uri": obj.get("profile_uri"),
            "sections": obj.get("sections"),
            "titles": obj.get("titles")
        })
        return _obj


