# coding: utf-8

"""
    nebula-api

    The public Nebula Labs API for access to pertinent UT Dallas data

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.schema_single_building_events_schema_section_with_time import SchemaSingleBuildingEventsSchemaSectionWithTime
from typing import Optional, Set
from typing_extensions import Self

class SchemaMultiBuildingEventsSchemaSectionWithTime(BaseModel):
    """
    SchemaMultiBuildingEventsSchemaSectionWithTime
    """ # noqa: E501
    buildings: Optional[List[SchemaSingleBuildingEventsSchemaSectionWithTime]] = None
    var_date: Optional[StrictStr] = Field(default=None, alias="date")
    __properties: ClassVar[List[str]] = ["buildings", "date"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SchemaMultiBuildingEventsSchemaSectionWithTime from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in buildings (list)
        _items = []
        if self.buildings:
            for _item_buildings in self.buildings:
                if _item_buildings:
                    _items.append(_item_buildings.to_dict())
            _dict['buildings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SchemaMultiBuildingEventsSchemaSectionWithTime from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "buildings": [SchemaSingleBuildingEventsSchemaSectionWithTime.from_dict(_item) for _item in obj["buildings"]] if obj.get("buildings") is not None else None,
            "date": obj.get("date")
        })
        return _obj


