# coding: utf-8

"""
    nebula-api

    The public Nebula Labs API for access to pertinent UT Dallas data

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.schema_api_response_schema_bucket_info import SchemaAPIResponseSchemaBucketInfo

class TestSchemaAPIResponseSchemaBucketInfo(unittest.TestCase):
    """SchemaAPIResponseSchemaBucketInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchemaAPIResponseSchemaBucketInfo:
        """Test SchemaAPIResponseSchemaBucketInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SchemaAPIResponseSchemaBucketInfo`
        """
        model = SchemaAPIResponseSchemaBucketInfo()
        if include_optional:
            return SchemaAPIResponseSchemaBucketInfo(
                data = openapi_client.models.schema/bucket_info.schema.BucketInfo(
                    contents = [
                        ''
                        ], 
                    created = '', 
                    name = '', 
                    updated = '', ),
                message = '',
                status = 56
            )
        else:
            return SchemaAPIResponseSchemaBucketInfo(
        )
        """

    def testSchemaAPIResponseSchemaBucketInfo(self):
        """Test SchemaAPIResponseSchemaBucketInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
