# coding: utf-8

"""
    nebula-api

    The public Nebula Labs API for access to pertinent UT Dallas data

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.schema_mazevo_event import SchemaMazevoEvent

class TestSchemaMazevoEvent(unittest.TestCase):
    """SchemaMazevoEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchemaMazevoEvent:
        """Test SchemaMazevoEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SchemaMazevoEvent`
        """
        model = SchemaMazevoEvent()
        if include_optional:
            return SchemaMazevoEvent(
                contact_name = '',
                date_time_end = '',
                date_time_start = '',
                event_name = '',
                organization_name = '',
                setup_minutes = 1.337,
                status_color = '',
                status_description = '',
                teardown_minutes = 1.337
            )
        else:
            return SchemaMazevoEvent(
        )
        """

    def testSchemaMazevoEvent(self):
        """Test SchemaMazevoEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
