# coding: utf-8

"""
    nebula-api

    The public Nebula Labs API for access to pertinent UT Dallas data

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.schema_api_response_schema_multi_building_events_schema_mazevo_event import SchemaAPIResponseSchemaMultiBuildingEventsSchemaMazevoEvent

class TestSchemaAPIResponseSchemaMultiBuildingEventsSchemaMazevoEvent(unittest.TestCase):
    """SchemaAPIResponseSchemaMultiBuildingEventsSchemaMazevoEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchemaAPIResponseSchemaMultiBuildingEventsSchemaMazevoEvent:
        """Test SchemaAPIResponseSchemaMultiBuildingEventsSchemaMazevoEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SchemaAPIResponseSchemaMultiBuildingEventsSchemaMazevoEvent`
        """
        model = SchemaAPIResponseSchemaMultiBuildingEventsSchemaMazevoEvent()
        if include_optional:
            return SchemaAPIResponseSchemaMultiBuildingEventsSchemaMazevoEvent(
                data = openapi_client.models.schema/multi_building_events_schema_mazevo_event.schema.MultiBuildingEvents-schema_MazevoEvent(
                    buildings = [
                        openapi_client.models.schema/single_building_events_schema_mazevo_event.schema.SingleBuildingEvents-schema_MazevoEvent(
                            building = '', 
                            rooms = [
                                openapi_client.models.schema/room_events_schema_mazevo_event.schema.RoomEvents-schema_MazevoEvent(
                                    events = [
                                        openapi_client.models.schema/mazevo_event.schema.MazevoEvent(
                                            contact_name = '', 
                                            date_time_end = '', 
                                            date_time_start = '', 
                                            event_name = '', 
                                            organization_name = '', 
                                            setup_minutes = 1.337, 
                                            status_color = '', 
                                            status_description = '', 
                                            teardown_minutes = 1.337, )
                                        ], 
                                    room = '', )
                                ], )
                        ], 
                    date = '', ),
                message = '',
                status = 56
            )
        else:
            return SchemaAPIResponseSchemaMultiBuildingEventsSchemaMazevoEvent(
        )
        """

    def testSchemaAPIResponseSchemaMultiBuildingEventsSchemaMazevoEvent(self):
        """Test SchemaAPIResponseSchemaMultiBuildingEventsSchemaMazevoEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
