# coding: utf-8

"""
    nebula-api

    The public Nebula Labs API for access to pertinent UT Dallas data

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_astra_events(self) -> None:
        """Test case for astra_events

        """
        pass

    def test_autocomplete_dag(self) -> None:
        """Test case for autocomplete_dag

        """
        pass

    def test_bucket_info(self) -> None:
        """Test case for bucket_info

        """
        pass

    def test_course_all(self) -> None:
        """Test case for course_all

        """
        pass

    def test_course_by_id(self) -> None:
        """Test case for course_by_id

        """
        pass

    def test_course_search(self) -> None:
        """Test case for course_search

        """
        pass

    def test_course_section_by_id(self) -> None:
        """Test case for course_section_by_id

        """
        pass

    def test_course_section_search(self) -> None:
        """Test case for course_section_search

        """
        pass

    def test_delete_bucket(self) -> None:
        """Test case for delete_bucket

        """
        pass

    def test_delete_object(self) -> None:
        """Test case for delete_object

        """
        pass

    def test_events(self) -> None:
        """Test case for events

        """
        pass

    def test_events_by_building(self) -> None:
        """Test case for events_by_building

        """
        pass

    def test_grade_aggregation_by_semester(self) -> None:
        """Test case for grade_aggregation_by_semester

        """
        pass

    def test_grade_aggregation_overall(self) -> None:
        """Test case for grade_aggregation_overall

        """
        pass

    def test_grade_aggregation_section_type(self) -> None:
        """Test case for grade_aggregation_section_type

        """
        pass

    def test_grades_by_course_id(self) -> None:
        """Test case for grades_by_course_id

        """
        pass

    def test_grades_by_professor_id(self) -> None:
        """Test case for grades_by_professor_id

        """
        pass

    def test_grades_by_section_id(self) -> None:
        """Test case for grades_by_section_id

        """
        pass

    def test_mazevo_events(self) -> None:
        """Test case for mazevo_events

        """
        pass

    def test_object_info(self) -> None:
        """Test case for object_info

        """
        pass

    def test_post_object(self) -> None:
        """Test case for post_object

        """
        pass

    def test_professor_all(self) -> None:
        """Test case for professor_all

        """
        pass

    def test_professor_by_id(self) -> None:
        """Test case for professor_by_id

        """
        pass

    def test_professor_course_by_id(self) -> None:
        """Test case for professor_course_by_id

        """
        pass

    def test_professor_course_search(self) -> None:
        """Test case for professor_course_search

        """
        pass

    def test_professor_search(self) -> None:
        """Test case for professor_search

        """
        pass

    def test_professor_section_by_id(self) -> None:
        """Test case for professor_section_by_id

        """
        pass

    def test_professor_section_search(self) -> None:
        """Test case for professor_section_search

        """
        pass

    def test_rooms(self) -> None:
        """Test case for rooms

        """
        pass

    def test_section_by_id(self) -> None:
        """Test case for section_by_id

        """
        pass

    def test_section_search(self) -> None:
        """Test case for section_search

        """
        pass

    def test_swagger(self) -> None:
        """Test case for swagger

        """
        pass

    def test_trends_course_section_search(self) -> None:
        """Test case for trends_course_section_search

        """
        pass

    def test_trends_professor_section_search(self) -> None:
        """Test case for trends_professor_section_search

        """
        pass


if __name__ == '__main__':
    unittest.main()
