# coding: utf-8

"""
    nebula-api

    The public Nebula Labs API for access to pertinent UT Dallas data

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.schema_multi_building_events_schema_mazevo_event import SchemaMultiBuildingEventsSchemaMazevoEvent

class TestSchemaMultiBuildingEventsSchemaMazevoEvent(unittest.TestCase):
    """SchemaMultiBuildingEventsSchemaMazevoEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchemaMultiBuildingEventsSchemaMazevoEvent:
        """Test SchemaMultiBuildingEventsSchemaMazevoEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SchemaMultiBuildingEventsSchemaMazevoEvent`
        """
        model = SchemaMultiBuildingEventsSchemaMazevoEvent()
        if include_optional:
            return SchemaMultiBuildingEventsSchemaMazevoEvent(
                buildings = [
                    openapi_client.models.schema/single_building_events_schema_mazevo_event.schema.SingleBuildingEvents-schema_MazevoEvent(
                        building = '', 
                        rooms = [
                            openapi_client.models.schema/room_events_schema_mazevo_event.schema.RoomEvents-schema_MazevoEvent(
                                events = [
                                    openapi_client.models.schema/mazevo_event.schema.MazevoEvent(
                                        contact_name = '', 
                                        date_time_end = '', 
                                        date_time_start = '', 
                                        event_name = '', 
                                        organization_name = '', 
                                        setup_minutes = 1.337, 
                                        status_color = '', 
                                        status_description = '', 
                                        teardown_minutes = 1.337, )
                                    ], 
                                room = '', )
                            ], )
                    ],
                var_date = ''
            )
        else:
            return SchemaMultiBuildingEventsSchemaMazevoEvent(
        )
        """

    def testSchemaMultiBuildingEventsSchemaMazevoEvent(self):
        """Test SchemaMultiBuildingEventsSchemaMazevoEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
