# coding: utf-8

"""
    nebula-api

    The public Nebula Labs API for access to pertinent UT Dallas data

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.schema_api_response_int import SchemaAPIResponseInt

class TestSchemaAPIResponseInt(unittest.TestCase):
    """SchemaAPIResponseInt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchemaAPIResponseInt:
        """Test SchemaAPIResponseInt
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SchemaAPIResponseInt`
        """
        model = SchemaAPIResponseInt()
        if include_optional:
            return SchemaAPIResponseInt(
                data = 56,
                message = '',
                status = 56
            )
        else:
            return SchemaAPIResponseInt(
        )
        """

    def testSchemaAPIResponseInt(self):
        """Test SchemaAPIResponseInt"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
