# coding: utf-8

"""
    nebula-api

    The public Nebula Labs API for access to pertinent UT Dallas data

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.schema_api_response_array_schema_building_rooms import SchemaAPIResponseArraySchemaBuildingRooms

class TestSchemaAPIResponseArraySchemaBuildingRooms(unittest.TestCase):
    """SchemaAPIResponseArraySchemaBuildingRooms unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchemaAPIResponseArraySchemaBuildingRooms:
        """Test SchemaAPIResponseArraySchemaBuildingRooms
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SchemaAPIResponseArraySchemaBuildingRooms`
        """
        model = SchemaAPIResponseArraySchemaBuildingRooms()
        if include_optional:
            return SchemaAPIResponseArraySchemaBuildingRooms(
                data = [
                    openapi_client.models.schema/building_rooms.schema.BuildingRooms(
                        building = '', 
                        rooms = [
                            ''
                            ], )
                    ],
                message = '',
                status = 56
            )
        else:
            return SchemaAPIResponseArraySchemaBuildingRooms(
        )
        """

    def testSchemaAPIResponseArraySchemaBuildingRooms(self):
        """Test SchemaAPIResponseArraySchemaBuildingRooms"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
