# coding: utf-8

"""
    nebula-api

    The public Nebula Labs API for access to pertinent UT Dallas data

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.schema_simple_professor import SchemaSimpleProfessor

class TestSchemaSimpleProfessor(unittest.TestCase):
    """SchemaSimpleProfessor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchemaSimpleProfessor:
        """Test SchemaSimpleProfessor
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SchemaSimpleProfessor`
        """
        model = SchemaSimpleProfessor()
        if include_optional:
            return SchemaSimpleProfessor(
                first_name = '',
                last_name = ''
            )
        else:
            return SchemaSimpleProfessor(
        )
        """

    def testSchemaSimpleProfessor(self):
        """Test SchemaSimpleProfessor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
