# coding: utf-8

"""
    nebula-api

    The public Nebula Labs API for access to pertinent UT Dallas data

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.schema_grade_data import SchemaGradeData

class TestSchemaGradeData(unittest.TestCase):
    """SchemaGradeData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchemaGradeData:
        """Test SchemaGradeData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SchemaGradeData`
        """
        model = SchemaGradeData()
        if include_optional:
            return SchemaGradeData(
                id = '',
                grade_distribution = [
                    56
                    ]
            )
        else:
            return SchemaGradeData(
        )
        """

    def testSchemaGradeData(self):
        """Test SchemaGradeData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
