# coding: utf-8

"""
    nebula-api

    The public Nebula Labs API for access to pertinent UT Dallas data

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.schema_api_response_string import SchemaAPIResponseString

class TestSchemaAPIResponseString(unittest.TestCase):
    """SchemaAPIResponseString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SchemaAPIResponseString:
        """Test SchemaAPIResponseString
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SchemaAPIResponseString`
        """
        model = SchemaAPIResponseString()
        if include_optional:
            return SchemaAPIResponseString(
                data = '',
                message = '',
                status = 56
            )
        else:
            return SchemaAPIResponseString(
        )
        """

    def testSchemaAPIResponseString(self):
        """Test SchemaAPIResponseString"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
